# Python CircleCI 2.0 configuration file
version: 2.2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/CicdQuote

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv main
            pip install -r requirements.txt
            pip install pycodestyle pytest pytest-cov
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pytest -v --cov